### ISSUE TITLE
Canvas support

### ISSUE THREAD

**Issue by namgk** [w3c/picture-in-picture#180] opened 2020-04-29 15:40 UTC
Hi there,

Is there any plan to support PiP for canvas stream as well?

There are some use cases such as animations are drawn on a canvas and people want to see it while working on something else.

I'm thinking about feeding the canvas stream to a video element, however, the canvas might be animated by a _requestAnimationFrame_ loop and when the tab is inactive, _requestAnimationFrame_ is paused.

Thanks.

**Comment by 1valdis** [comment] 2020-05-01 09:15
I wanted to go this way too to make at least something interactive out of PiP video element, but seems like even streaming from canvas won't help if requestAnimationFrame is paused... Maybe use more stupid way with setInterval then?

**Comment by 1valdis** [comment] 2020-05-03 11:37
I tried setInterval, but Chrome throttles it to 1 second for background. I also tried OfflineCanvas with Worker (I heard that setInterval isn't throttled in a worker), but it works as expected for a few seconds and then starts hanging also. What the hell. Can we do something to smoothly animate canvas for PiP, please?

**Comment by beaufortfrancois** [comment] 2020-05-04 05:46
I've played a bit with Picture-in-Picture and canvas at https://beaufortfrancois.github.io/sandbox/media/picture-in-picture-timer and it seems to be working fine for me with `requestAnimationFrame`.
Can you share your playground page so that I can have a look?

**Comment by 1valdis** [comment] 2020-05-04 06:19
I've made 3 demos:
1) [using requestAnimationFrame](https://enl-dp-ua.github.io/nfc-clock/request-animation-frame.html) ([src](https://github.com/Enl-DP-UA/nfc-clock/blob/master/request-animation-frame.html))
2) [using setInterval](https://enl-dp-ua.github.io/nfc-clock/set-interval.html) ([src](https://github.com/Enl-DP-UA/nfc-clock/blob/master/set-interval.html))
3) [using setInterval, Worker and OffscreenCanvas](https://enl-dp-ua.github.io/nfc-clock/set-interval-worker-offscreen.html) ([src](https://github.com/Enl-DP-UA/nfc-clock/blob/master/set-interval-worker-offscreen.html))

The positive result is, as you said, only for requestAnimationFrame, and only for Desktop. (I still observed a little hangs for a few seconds when using requestAnimationFrame, but otherwise it works smooth).

Hovewer, on Android, which is my main target for this API, all 3 demos hang as soon as I try to switch app: [see screen recording](https://drive.google.com/file/d/178hn4foGdpsrxKxB8t1h_JAcbofBh0DB/view?usp=sharing).

**Comment by beaufortfrancois** [comment] 2020-05-04 07:21
Picture-in-Picture Web API has still not launched on Android. It still has some issues IIRC. @mounirlamouri may tell you more.

**Comment by 1valdis** [comment] 2020-05-04 08:22
Yeah I got to enable it with a flag. And that would be OK for my use case; the problem is that it hangs though.

**Comment by mounirlamouri** [comment] 2020-05-11 19:43
On Android, the API is available behind a flag at the moment but given that we didn't launch, it's possible that some bugs are still around.

**Comment by beaufortfrancois** [comment] 2020-06-11 06:46
As this seems to be a Chrome issue, I'm going to close this.
Feel free to open a Chromium bug at https://crbug.com/?q=component:Blink%3EMedia%3EPictureInPicture and we'll make sure it's triaged properly.

**Closed by beaufortfrancois** 2020-06-11 06:46 UTC

**Comment by guest271314** [comment] 2020-06-18 14:34
@1valdis `ReadableStream` can be used instead of `requestAnimationFrame()` https://github.com/guest271314/MediaFragmentRecorder/blob/imagecapture-audiocontext-readablestream-writablestream/MediaFragmentRecorder.html.
